# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker Buildx'
description: 'GitHub Action to set up Docker Buildx'
author: 'crazy-max'
branding:
  color: 'blue'
  icon: 'truck'

inputs:
  buildx-version:
    description: 'Buildx version. Example: v0.3.0'
    default: 'latest'
    required: false
  skip-cache:
    description: 'Deprecated. No longer useful. Will not be supported after June 15, 2020'
    deprecationMessage: 'The skip-cache input will not be supported after June 15, 2020. No longer useful'
    required: false
  qemu-version:
    description: 'QEMU static binaries Docker image version. Example: 4.2.0-7'
    default: 'latest'
    required: false

outputs:
  platforms:
    description: 'Available platforms (comma separated)'

runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
