name: lint

on:
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - 'src/*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Node
        uses: actions/setup-node@v2.0.0
      -
        name: Setup TS
        run: npm install tslint typescript -g
      -
        name: Lint check
        run: tslint './src/*.ts'
