name: ncc

on:
  repository_dispatch:
    types:
      - ncc
  push:
    branches:
      - master
      - releases/v*
    paths-ignore:
      - '**.md'

jobs:
  ncc:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        run: |
          npm install
          npm run format
          npm run build
      -
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update generated content"
          title: "Update generated content"
          branch: ncc
          branch-suffix: timestamp
