name: test

on:
  push:
    branches:
      - master
      - releases/v*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install
        run: npm install
      -
        name: Test
        run: npm run test
      -
        name: Audit packages
        run: npm audit --audit-level=high
      -
        name: Upload coverage
        uses: codecov/codecov-action@v1.0.7
        if: success()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
